# Generated by Django 3.1.4 on 2020-12-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_invdations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invdations',
            new_name='Invitations',
        ),
    ]
