# Generated by Django 3.1.4 on 2020-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.DateField(),
        ),
    ]
