# Generated by Django 3.1.4 on 2020-12-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20201215_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='release_year',
            new_name='release',
        ),
    ]
